config/routes.rb
Rails.application.routes.draw do
  scope :admin do
    devise_for :admins, controllers: { sessions: 'admin/admins/sessions' }
  end
  namespace :admin do
    root to: 'main#index'

    resources :teachers, except: :show
    resources :disciplines, except: :show
    resources :admins, except: :show
    
    resources :courses, except: :show do
      resources :lessons, except: :show
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/views/admin/shared/_main_menu.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'OnlineSchool', admin_root_path, class: 'navbar-brand'
    - if current_admin
      /! Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          - @main_menu.each do |item, options|
            /li.active
              /a href="#" 
                | /Link
                /span.sr-only (current)
            li class=(options[:active] ? 'active' : '')
              = link_to options[:path] do
                = options[:name]
                - if options[:active]
                  span.sr-only (current)
          
        ul.nav.navbar-nav.navbar-right
          li.dropdown
            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
              | #{current_admin.first_name} #{current_admin.last_name}
              span.caret
            ul.dropdown-menu 
              li
                = link_to 'Вийти', destroy_admin_session_path, method: :delete
      /! /.navbar-collapse
    /! /.container-fluid